# This is the configuration used to check the rubocop source code.

require: rubocop-rspec
inherit_from:
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - 'docker-compose/**/*'
    - 'examples/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'vendor/bundle/**/*'
  TargetRubyVersion: 2.6
Style/Alias:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/LineLength:
  Max: 100

Style/RegexpLiteral:
  EnforcedStyle: mixed

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

RSpec/InstanceVariable:
  Enabled: false

Lint/SuppressedException:
  Enabled: false
